# markdownlint configuration for this repo
# Relax rules to allow inline HTML and long lines common in badges/cards
MD013: false           # Line length
MD033: false           # Inline HTML
MD034: false           # Bare URLs (resume contains links)
MD007:
  indent: 2            # Allow 2-space indent for nested lists
MD022:
  lines_above: 1
  lines_below: 1
MD032: true            # Require blank lines around lists
MD012: true            # No multiple consecutive blank lines
